routes/web.php
<?php

use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware("guest")->group(function(){
    Route::get("/user/register", [UserController::class, 'register'])->name('register');
    Route::get("/user/login", [UserController::class, 'login'])->name('login');
    Route::post("/user/store-register", [UserController::class, 'storeRegister'])->name('store-register');
    Route::post("/user/authenticate", [UserController::class, 'authenticate'])->name('authenticate');
});

Route::post('user/logout', [UserController::class, 'logout'])->name("logout")->middleware("auth");
Route::resource("/user", UserController::class)->middleware('auth');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Exception;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $context = [
            "users" => User::all(),
            "title" => "Semua User"
        ];

        return view("user.index",$context);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $context = [
            "title" => "Buat User"
        ];
        return view("user.create",$context);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->password !== $request->confirm_password){
            return redirect()->back()->with('swal-fail-message','Konfirmasi Password Dan Password Harus Sama!');
        }

        try {
            User::create([
                "name" => $request->name,
                "password" => bcrypt($request->password),
                "email" => $request->email
            ]);
        }
        catch(Exception $fail)
        {
            var_dump($fail->getMessage());
            throw $fail;
        }

        return redirect()->back()->with('swal-success-message', 'Berhasil membuat User Baru!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $context = [
            "title" => "Edit $user->name",
            "user" => $user
        ];
        return view("user.edit", $context);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        try {
            $user->update([
                "name" => $request->name,
                "email" => $request->email
            ]);
        }
        catch(Exception $fail){
            throw $fail;
        }

        return redirect()->back()->with("swal-success-message", "Berhasil Ubah Data Pengguna!");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->back()->with("swal-success-message",'berhasil menghapus pengguna');
    }

    public function register()
    {
        $context = ['title' => 'Register Wangi'];
        return view("user.register",$context);
    }

    public function storeRegister(Request $request)
    {
        if($request->password !== $request->confirm_password){
            return redirect()->back()->with('swal-fail-message','Konfirmasi Password Dan Password Harus Sama!');
        }

        try {
            User::create([
                "name" => $request->name,
                "password" => bcrypt($request->password),
                "email" => $request->email
            ]);
        }
        catch(Exception $fail)
        {
            var_dump($fail->getMessage());
            throw $fail;
        }

        return redirect()->to(route('login'))->with('swal-success-message', 'selamat akun anda telah berhasil terdaftar, silahkan login sekarang');

    }

    public function login()
    {
        $context = ['title' => 'Login'];
        return view("user.login", $context);
    }

    public function authenticate(Request $request)
    {
        $credentials = $request->validate([
            'email' => ['required', 'email'],
            'password' => ['required'],
        ]);
 
        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();
 
            return redirect()->intended('/user');
        }
 
        return back()->withErrors([
            'email' => 'Email Atau Password Salah.',
        ])->onlyInput('email');
    }

    public function logout(Request $request)
    {    
        Auth::logout();
    
        $request->session()->invalidate();
    
        $request->session()->regenerateToken();
    
        return redirect('/');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  @vite('resources/css/app.css')
  <title class="capitalize">{{ $title ?? 'page' }}</title>
  <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <div id="message" swal-success-message="{{ session("swal-success-message") }}" swal-fail-message="{{ session("swal-fail-message") }}">
        @if(session()->has("swal-success-message"))
          <script>
            Swal.fire(
              "Berhasil",
              document.getElementById('message').getAttribute("swal-success-message"),
              "success"
            );
          </script>
        @elseif(session()->has("swal-fail-message"))
        <script>
            Swal.fire(
              "Oops",
              document.getElementById('message').getAttribute("swal-fail-message"),
              "error"
            );
          </script>
        @endif
    </div>
    <nav class="p-4 flex align-middle justify-between bg-purple-600 text-white">
        <div class="px-5">
            <a href="{{ route('user.index') }}" class="font-bold text-2xl">CRUD WANGI</a>
        </div>
        <div class="">
            <a href="{{ route('user.index') }}" class="text-md md:mx-2">Home</a>
            <a href="{{ route('user.create') }}" class="text-md md:mx-2">Buat User</a>
            @auth
            <form action="{{ route('logout') }}" method="post" class="inline">
              @csrf
              <button class="text-md md:mx-2">Logout</button> 
            </form>
            @endauth
            @guest
            <a href="{{ route('login') }}" class="text-md md:mx-2">Login</a>   
            @endguest

        </div>
    </nav>

    <div class="md:px-10 md:py-5">
        @yield('content')
    </div>
    @yield('js')
    <script src="{{ url("js/index.js") }}"></script>
</body>
</html>

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{ route('user.store') }}" method="post" class="shadow p-5 w-8/12 mx-auto">
        <h1 class="text-3xl font-bold text-purple-500 my-3 text-center">Buat User</h1>
        @csrf
        <div class="grid grid-cols-1 gap-4 ">
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Name
                    </span>
                        <input type="text" name="name" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" placeholder="ex. Adam" />
                    </label>
            </div>
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Email
                    </span>
                    <input type="email" name="email" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" placeholder="you@example.com" />
                </label>
            </div>
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Password
                    </span>
                    <input type="password" name="password" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" required/>
                </label>
            </div>
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Konfirmasi Password
                    </span>
                    <input type="password" name="confirm_password" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" required/>
                </label>
            </div>
            <div>
                <button class="px-5 py-1  bg-purple-500 rounded-sm text-white">Buat</button>
                 <a href="{{ route('user.index') }}" class="btn rounded px-5 py-2 border-purple-500 font-bold text-purple-500 hover:bg-purple-500 hover:text-white">Home</a>
            </div>
        </div>
    </form>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{ route('user.update', ['user' => $user]) }}" method="post" class="shadow p-5 w-8/12 mx-auto">
        <h1 class="text-3xl font-bold text-purple-500 my-3 text-center capitalize">Edit User {{ $user->name }}</h1>
        @csrf
        @method("PUT")
        <div class="grid grid-cols-1 gap-4 ">
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Nama
                    </span>
                    <input value="{{ $user->name }}" type="text" name="name" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" required />
                </label>
            </div>
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Email
                    </span>
                    <input value="{{ $user->email }}" type="email" name="email" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" placeholder="you@example.com" required/>
                </label>
            </div>
           
            <div>
                <button class="px-5 py-1 bg-purple-500 rounded-sm text-white">Ubah Data</button>
                <a href="{{ route('user.index') }}" class="btn rounded px-5 py-2 border-purple-500 font-bold text-purple-500 hover:bg-purple-500 hover:text-white">Kembali</a>
            </div>
        </div>
        
    </form>
@endsection

resources/views/user/index.blade.php
@extends("layouts.app")

@section('content')

<div class="flex flex-col">
  <div>
    <p class="text-purple-600 text-xl font-bold">Tabel Pengguna</p> 
  </div>
  <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
      <div class="overflow-hidden">
        <table class="min-w-full">
          <thead class="border-b">

            <tr class="bg-purple-400 text-white">
              <th scope="col" class="text-sm font-medium px-6 py-4 text-left">
                #
              </th>
              <th scope="col" class="text-sm font-medium px-6 py-4 text-left">
                Nama
              </th>
              <th scope="col" class="text-sm font-medium px-6 py-4 text-left">
                Email
              </th>
              <th scope="col" class="text-sm font-medium px-6 py-4 text-left">
                Aksi
              </th>
            </tr>
          </thead>
          <tbody>
            @foreach($users as $user)
            <tr class="border-b">
              <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{ $loop->iteration }}</td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap capitalize">
                {{ $user->name }}
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap capitalize">
               {{ $user->email }}
              </td>
              <td class="text-sm text-gray-900 font-light px-6 py-4 whitespace-nowrap capitalize">
                <div class="inline">
                  <a href="{{ route('user.edit',['user' => $user]) }}" class="btn rounded px-5 py-2 bg-purple-500 font-bold text-white">Edit</a>
                </div>
                <form action="{{ route('user.destroy',['user' => $user]) }}" method="post" class="inline del-btn">
                  @csrf
                  @method("DELETE")
                  <button type="button" class="del-btn rounded px-5 py-2 border-purple-500 font-bold text-purple-500 hover:bg-purple-500 hover:text-white">Hapus</button>
                </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/user/login.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{ route('authenticate') }}" method="post" class="shadow p-5 w-8/12 mx-auto">
        <h1 class="text-3xl font-bold text-purple-500 my-3 text-center">Login CrudWangi</h1>
        @csrf
        <div class="grid grid-cols-1 gap-4 ">
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Email
                    </span>
                    <input type="email" value="{{ old('email','') }}" name="email" class="@error('email') border-red-500 @enderror  mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" placeholder="you@example.com" />
                    @error('email') 
                    <span class="text-red-500">{{ $message }}</span> @enderror
                </label>
            </div>
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Password
                    </span>
                    <input type="password" name="password" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" required/>
                </label>
            </div>
           
            <div>
                <button class="px-5 py-1 bg-purple-500 rounded-sm text-white">Login</button>
            </div>
        </div>
        <div class="my-3 text-center">
            <span class="text-gray-500 ">Belum Mempunyai Akun? <a href="{{ route('register') }}" class="text-purple-500">Register Disini</a></span>
        </div>
    </form>
@endsection

resources/views/user/register.blade.php
@extends('layouts.app')

@section('content')
    <form action="{{ route('store-register') }}" method="post" class="shadow p-5 w-8/12 mx-auto">
        <h1 class="text-3xl font-bold text-purple-500 my-3 text-center">Register CrudWangi</h1>
        @csrf
        <div class="grid grid-cols-1 gap-4 ">
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Name
                    </span>
                        <input type="text" name="name" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" placeholder="ex. Adam" />
                    </label>
            </div>
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Email
                    </span>
                    <input type="email" name="email" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" placeholder="you@example.com" />
                </label>
            </div>
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Password
                    </span>
                    <input type="password" name="password" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" required/>
                </label>
            </div>
            <div>
                <label class="block">
                    <span class="after:content-['*'] after:ml-0.5 after:text-red-500 block text-sm font-medium text-slate-700">
                        Konfirmasi Password
                    </span>
                    <input type="password" name="confirm_password" class="mt-1 px-3 py-2 bg-white border shadow-sm border-slate-300 placeholder-slate-400 focus:outline-none focus:border-purple-500 focus:ring-purple-500 block w-full rounded-md sm:text-sm focus:ring-1" required/>
                </label>
            </div>
            <div>
                <button class="px-5 py-1  bg-purple-500 rounded-sm text-white">Register</button>
            </div>
        </div>
        <div class="my-3 text-center">
            <span class="text-gray-500 ">Sudah Mempunyai Akun? <a href="{{ route('login') }}" class="text-purple-500">Login Disini    </a></span>
        </div>
    </form>
@endsection